/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.74
 * Generated at: 2023-05-25 00:03:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javax.servlet.jsp.tagext.TryCatchFinally;
import java.sql.*;
import javax.sql.*;
import java.io.*;
import java.util.*;

public final class insert2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.sql");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("javax.servlet.jsp.tagext.TryCatchFinally");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- JDBC 사용시 필요한 임포트 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');

    request.setCharacterEncoding("UTF-8");

      out.write("\r\n");
      out.write("<HTML>\r\n");
      out.write("<HEAD>\r\n");
      out.write("</HEAD>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("	p {\r\n");
      out.write("		font-size :20px;\r\n");
      out.write("		font-weight : bold;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	input {\r\n");
      out.write("	height: 60px;\r\n");
      out.write("	width: 300px;\r\n");
      out.write("	border-radius: 15px;\r\n");
      out.write("	font-size: 20px;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	button {\r\n");
      out.write("    background-color:#6a6a76;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    border:none;\r\n");
      out.write("    border-radius:10px;\r\n");
      out.write("    box-shadow: 0px 0px 2px 2px rgb(102 101 101);\r\n");
      out.write("    height: 50px;\r\n");
      out.write("    width: 150px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    font-size: 20px;\r\n");
      out.write("    }\r\n");
      out.write("    a {\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	color : white;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	h1 {\r\n");
      out.write("	padding-left : 100px;\r\n");
      out.write("	}\r\n");
      out.write("    \r\n");
      out.write("</style>\r\n");
      out.write("<BODY>\r\n");
      out.write("	<!-- Mysql데이터 베이스 연결 -->\r\n");
      out.write("	");


	Connection conn = null;
	try {
		String url = "jdbc:mysql://localhost:33060/kopo07?useSSL=false";
		String user = "root";
		String pw = "1234";
		Class.forName("com.mysql.cj.jdbc.Driver");
		conn = DriverManager.getConnection(url, user, pw);
		Statement stmt = conn.createStatement();

        //======================= 트와이스 테이블에 값넣기 =======================

		String name = "";
		int id = 0;
		int korea = 0;
		int english = 0;
		int math = 0;

        try {

        name = request.getParameter("name");
        id = Integer.parseInt(request.getParameter("id"));
        korea = Integer.parseInt(request.getParameter("kor"));
        english = Integer.parseInt(request.getParameter("eng"));
        math = Integer.parseInt(request.getParameter("mat"));

        } catch(Exception e) {
        }

        if(name.equals("")) {
            name = "없음";
        }
	
        stmt.execute("insert into twice value('"+name+"'," + id + "," + korea + "," + english + "," + math + ");");
        
        stmt.close(); 
        conn.close(); 
    
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <h1>테이블 값 넣기 성공!!</h1>\r\n");
      out.write("\r\n");
      out.write("		<p>이름 : <input type=\"text\" readonly value=\"");
      out.print( name);
      out.write("\"></p>\r\n");
      out.write("		<p>학번 : <input type=\"text\" readonly value=\"");
      out.print( id);
      out.write("\"></p>\r\n");
      out.write("		<p>국어 : <input type=\"text\" readonly value=\"");
      out.print( korea);
      out.write("\"></p>\r\n");
      out.write("		<p>영어 : <input type=\"text\" readonly value=\"");
      out.print( english);
      out.write("\"></p>\r\n");
      out.write("		<p>수학 : <input type=\"text\" readonly value=\"");
      out.print( math);
      out.write("\"></p>\r\n");
      out.write("\r\n");
      out.write("		<div style=\"padding-left : 125px\">\r\n");
      out.write("			<button>\r\n");
      out.write("				<a href=\"./intro.html\" target=\"main\">첫페이 가기</a>\r\n");
      out.write("			</button>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");

	} catch (SQLException e) {
        
	
      out.write("\r\n");
      out.write("		<h1>테이블을 우선 생성해주세요!!</h1>\r\n");
      out.write("	");

	}
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("</BODY>\r\n");
      out.write("</HTML>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
