/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.74
 * Generated at: 2023-05-25 01:24:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javax.servlet.jsp.tagext.TryCatchFinally;
import java.sql.*;
import javax.sql.*;
import java.io.*;
import java.util.*;

public final class selectAll_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.sql");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("javax.servlet.jsp.tagext.TryCatchFinally");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- JDBC 사용시 필요한 임포트 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<HTML>\r\n");
      out.write("<HEAD>\r\n");
      out.write("</HEAD>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("table {\r\n");
      out.write("  border-collapse: separate;\r\n");
      out.write("  border-spacing: 0;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("}\r\n");
      out.write("th,\r\n");
      out.write("td {\r\n");
      out.write("  padding: 6px 15px;\r\n");
      out.write("}\r\n");
      out.write("th {\r\n");
      out.write("  background: #42444e;\r\n");
      out.write("  color: #fff;\r\n");
      out.write("  text-align: left;\r\n");
      out.write("}\r\n");
      out.write("tr:first-child th:first-child {\r\n");
      out.write("  border-top-left-radius: 6px;\r\n");
      out.write("}\r\n");
      out.write("tr:first-child th:last-child {\r\n");
      out.write("  border-top-right-radius: 6px;\r\n");
      out.write("}\r\n");
      out.write("td {\r\n");
      out.write("  border-right: 1px solid #c6c9cc;\r\n");
      out.write("  border-bottom: 1px solid #c6c9cc;\r\n");
      out.write("}\r\n");
      out.write("td:first-child {\r\n");
      out.write("  border-left: 1px solid #c6c9cc;\r\n");
      out.write("}\r\n");
      out.write("tr:last-child td:first-child {\r\n");
      out.write("  border-bottom-left-radius: 6px;\r\n");
      out.write("}\r\n");
      out.write("tr:last-child td:last-child {\r\n");
      out.write("  border-bottom-right-radius: 6px;\r\n");
      out.write("}\r\n");
      out.write("#clickhere {\r\n");
      out.write("    text-decoration : none;\r\n");
      out.write("    font-weight : bold;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<BODY>\r\n");
      out.write(" \r\n");
      out.write("	<!-- Mysql데이터 베이스 연결 -->\r\n");
      out.write("	");


	Connection conn = null;
	try {
		String url = "jdbc:mysql://localhost:33060/kopo07?useSSL=false";
		String user = "root";
		String pw = "1234";

		Class.forName("com.mysql.cj.jdbc.Driver");
		conn = DriverManager.getConnection(url, user, pw);
		Statement stmt = conn.createStatement();


        //======================= 트와이스 테이블에 전체 조회하기 =======================

        ResultSet rset = stmt.executeQuery("select * from twice");

    
      out.write("\r\n");
      out.write("\r\n");
      out.write("<center>\r\n");
      out.write("    <table>\r\n");
      out.write("        <thead>\r\n");
      out.write("            <tr id=\"thead\">\r\n");
      out.write("                <th>이름</th>\r\n");
      out.write("                <th>번호</th>\r\n");
      out.write("                <th>국어점수</th>\r\n");
      out.write("                <th>영어점수</th>\r\n");
      out.write("                <th>수학점수</th>\r\n");
      out.write("            </tr> \r\n");
      out.write("        </thead> \r\n");
      out.write("\r\n");
      out.write("    ");


       while(rset.next()) {

        String name = rset.getString(1);
        int id = rset.getInt(2);
        int kor = rset.getInt(3);
        int eng = rset.getInt(4);
        int mat = rset.getInt(5);

    
      out.write("\r\n");
      out.write("    <tbody>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td><a id=\"clickhere\" href=\"select.jsp?id=");
      out.print(id);
      out.write('"');
      out.write('>');
      out.print(name);
      out.write("</a></td>\r\n");
      out.write("            <td>");
      out.print(id);
      out.write("</td>\r\n");
      out.write("            <td>");
      out.print(kor);
      out.write("</td>\r\n");
      out.write("            <td>");
      out.print(eng);
      out.write("</td>\r\n");
      out.write("            <td>");
      out.print(mat);
      out.write("</td>\r\n");
      out.write("        </tr>  \r\n");
      out.write("    </tbody>\r\n");
      out.write("    ");

       }
    
    stmt.close(); 
    conn.close(); 

	} catch (SQLException e) {
        
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<h1>테이블을 우선 생성해주세요!!</h1>\r\n");
      out.write("\r\n");
      out.write("	");

	}
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </table>\r\n");
      out.write("</center>\r\n");
      out.write("\r\n");
      out.write("</BODY>\r\n");
      out.write("</HTML>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
